# -*- coding: utf-8 -*-
"""CSV Read.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wn33yaZJY3rpXN4WgpVJGQI4p_oHY9zV
"""

from google.colab import files


uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['Social_Network_Ads.csv']))
print(df)