# -*- coding: utf-8 -*-
"""CSV Read.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wn33yaZJY3rpXN4WgpVJGQI4p_oHY9zV
"""

from google.colab import files


uploaded = files.upload()

import pandas as pd
import io

df = pd.read_csv(io.BytesIO(uploaded['Social_Network_Ads.csv']))
print(df)

# import modules
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# read the dataset
df = pd.read_csv('Social_Network_Ads.csv')

# get the locations
X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# split the dataset
X_train, X_test, y_train, y_test = train_test_split(
	X, y, test_size=0.05, random_state=0)

X_train

X_test